# Generated by Django 5.1.1 on 2024-09-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlModels', '0003_citydata_place_img_citydata_place_img_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citydata',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
